### ISSUE TITLE
Combat

### ISSUE THREAD

**Issue by rheadkid** [KVonGit/Quest-Group_Project#3]
I'm not help here at all. Never have been an RPG guy...

**Comment by DarkLizerd** [comment]
We will need the standard, game wide set of stats, I would start with the 6 DnD standards first, skill set, And expand as needed. But, if your world does not require them, then it doesn't matter that the player is level 35 in swords, and a 95 strength... if you say he can't move the 20 lb rock, then he can't move the 20 lb rock.

**Comment by hegemonkhan** [comment]
I have lots of ideas, but no personal experience in what are good designs and/or mechanics, for RPG stuff (I'm just starting to make a game, trying to come up with such code... 5 years of quest... so far... lol), however, I have played many many many RPGs, so I'm very knowledgeable about many different designs and/or mechanics.

---------

we need to decide on how RPG (leveling/stats and etc) heavy or not, the game is going to be. And then what we're going to do/have.

Then, we can get done to the specifics of this stuff

--------

unlike probably most of you guys, I'm not very familar with using 'dice rolling' for values. So, I've been coming up with a few (so far) ways of doing stuff/mechanics on my own, and not using 'dice rolling', but I do use randomization for some stuff, just not specifically with using how 'dice rolling' works.

**Comment by XanMag** [comment]
I also have no experience with DnD-like stats or RPG in text adventures.  I have just started to dabble in it in X3 but my system is VERY simple without a LOT of weapons or stats.  It's basically, IF you have 'feather' you have a chance of hitting for some number between 1-3, IF you have 'frying pan' you have a chance of hitting 10-15, and IF you have... blah blah blah.  On top of that, I plan on having less than 10 total encounters with monsters needing slayed.

I have no experience coding complex stats and I have never used a library for anything.  I'm sure it is simple, but... well, there you have it.

**Comment by rheadkid** [comment]
>I have no experience coding complex stats and I have never used a library for anything. I'm sure it is simple, but... well, there you have it.

I Second That Emotion.

Except the library part.

I was afraid, but you pretty much just cut and paste the <object> or <whatever> section into a new file, nested between <library> and </library>.

Cut and dry, in the end.

I never found out if it needs the \<!DOCTYPE, so I just put it to be safe. It works. (Same doctype as the game files, by the by.)

**Comment by hegemonkhan** [comment]
Pixie uses that for some kind of check, though I'm not exactly sure what it's for myself, maybe it has something to do with HTML (browsers / web-sites-pages ) being able to read it, as Pixie uses 'XML', for his libraries, so maybe it's a way of telling the HTML/browser/web-site-page what language (and/or the version of the language) it is to read your library as.

**Comment by ThePix** [comment]
I see two broad approaches here. The first is puzzle based; if the player has the sword and perhaps the ability, he can defeat the zombie. The puzzle is getting the sword, or working out that you need to cut off its head or whatever. There are no stats, no hit points, etc. No randomness. Spells are about getting past obstacles, rather than winning combat (and that would fit the spell list at ifwiki). A very simple character creation process or none at all.

The other approach is combat-orientated, where combat is resolved by rolling virtual dice like a table-top RPG. The player has stats, and defeats the zombie by reducing its hits to zero. Proably has a lot of options in character development, and the player stats likely increase over the game.

The former would be easier, and more in keeping with the old school vibe that seems what we are going for, and I think would be my choice, though I am not that bothered.

If we go for the latter, I would very much recommend using my CombatLib, because combat is very complicated, and it means most of the work is done, and also various aspects are already decided.

**Comment by rheadkid** [comment]
>  puzzle based; if the player has the sword and perhaps the ability, he can defeat the zombie. The puzzle is getting the sword, or working out that you need to cut off its head or whatever. There are no stats, no hit points, etc. No randomness. Spells are about getting past obstacles, rather than winning combat (and that would fit the spell list at ifwiki). A very simple character creation process or none at all.
The former would be easier, and more in keeping with the old school vibe that seems what we are going for, and I think would be my choice, though I am not that bothered.

It would be easier for us and the player.

I vote for this one. (Maybe the sequel will be more of an RPG...)

**Comment by DarkLizerd** [comment]
Puzzle based combat would be the easiest to workout.
But, here is another option, maybe for later, for more options in battle.
RPG combat is more roll to hit, and keep rolling until someone dies...
I had, may still do, and old, 1985ish, game called Gladiator. You and one opponent are in the arena, same HP, not other stat used. The only thing you could control is your focus, (attack or defense).
You would set your attacking rating (0 to 100), and the remainder was applied to your defense. Then, based on your attack, to your opponent's defense, determined your percent chance to hit. 
For a berserker attack, you may use 95% for your attack, leaving 5%. Much easer to get a hit and a greater chance to hit hard (lots of damage) BUT, with a 5% on your defense, you would be easy to hit.
You can change this with every round, thereby simulating a real fight.

**Comment by rheadkid** [comment]
@DarkLizerd 

That was an excellent explanation and a good idea!

Do you just do it one command at a time?

\> SET ATTACK 95
Berserker mode initiated! (Hope you don't get hit!)

\> ATTACK THE BASTARD
Two things happen.
1. You throw a right cross
2. The bastard hits the dirt

**Comment by DarkLizerd** [comment]
It is set at each combat round. 
I don't think you needed a second "attack" command, you hit right after you set it...
But, like I said, 1985ish and I haven't seen it since, I will need to dig up, and set up my old Atari and see if I still have it.
But descriptive combat, is much better than: "You hit it for 5 points."
More work required to write it, but much better when reading it!
(Funny that I thought of this when I just woke up this morning...)

**Comment by rheadkid** [comment]
@DarkLizerd 

I refer to **Bruce Lee's Fighting Method** when I need to describe a good butt-kicking.

It's got most of his old notes in it, and he explained each motion in a way I could NEVER come close to.

**Comment by ThePix** [comment]
Back in the eightiers I played Rolemaster, a tabletop RPG, with a similar mechanic. As I recall, everyone put everything on attack!

If I was going to do that for Quest, I would put a slider on the screen, so the player could set that for the percentage, then do the attack command in one turn.

The real issue is how do you make the decision tactical? In what situations is 5% preferable to 95%. If there are a group of you, the one the big bad is going for defends, the rest pile in. If there is just you, you are going to be better off killing it fast.

It is potentially an interesting mechanics, but not for this project, in my opinion.

**Comment by DarkLizerd** [comment]
(for a closed issue, this one seem a bit busy...)
You mix it up, works best against a human opponent.
An all out attack, 90%...
Followed by a defensive round, 20%...
then a balanced one, 50%
Defend: 10%
Kill shot: 100%
(and hope "to the deity of your choice!" you kill it!!!) 
Remember, it your attack is set to 90%, that mean your defense in only 10%.
As a base value, you have a 90% chance to hit, and a 90% chance to get hit.
If you are defending, 10% attack, 90% defense, you most likely will not hit, but, most likely, you will not get hit.
If "it" goes "Berserker mode", 95% attack, and you are defending that round, say 15% attack, 85% def. It should have about a 10% chance to hit you. And, you would have about a 10% chance to hit it.
But, if you both go "Berserker mode", say, both at 95%,then you have a 90% chance to hit each other...
All combat happens at the same time, you could kill each other in the same round.

If nothing else, this could be used in combat in other games as well.

**Comment by rheadkid** [comment]
I only closed most of them because it was so hard to sort through it all.

As soon as I get done playing with my example dimension, I'm going to open a couple up. In order of relevancy.

After we get a solid ruling on what to put down for the genre, of course...

**Comment by rheadkid** [comment]
This one and magic need to be sorted out before we know what all we can do in our stories.

**Comment by KVonGit** [comment]
I believe we've decided on simple combat, so this issue is CUH-LOSED.
